set(DL_URL https://github.com/dlfcn-win32/dlfcn-win32)
set(DL_TAG v1.3.0)
set(DL_INCLUDE_DIR ${CMAKE_BINARY_DIR}/_deps/dlfcn-win32/include)

if(WIN32)
    cmake_policy(SET CMP0048 OLD)
    FetchContent_Declare(dl GIT_REPOSITORY ${DL_URL} GIT_TAG ${DL_TAG})
    FetchContent_MakeAvailable(dl)
    include_directories(${DL_INCLUDE_DIR})
    find_library(LIBDL dlfcn REQUIRED HINTS ${CMAKE_BINARY_DIR}/_deps/dlfcn-win32-src/lib)
else()
    find_library(LIBDL dl REQUIRED)
endif()
