name: CrossPlatform

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
        matrix:
            os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'

    - name: Preparation
      shell: bash
      run: ./ci/prepare.sh $BUILD_TYPE -DAVM_USE_GC=OFF

    - name: Build
      shell: bash
      run: ./ci/build-lib.sh $BUILD_TYPE
