name: CrossPlatform

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
        fail-fast: false
        matrix:
            os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'

    - name: Prepare
      shell: bash
      run: ./ci/submodules.sh

    - name: Configure
      shell: bash
      run: cmake -S . -B ./build

    - name: Build
      shell: bash
      run: cmake --build ./build --config $BUILD_TYPE
