name: Docs

on: [push]

env:
  BUILD_TYPE: Release
  SRC_DIR: ${{github.workspace}}
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docs
      shell: bash
      working-directory: ${{env.SRC_DIR}}
      run: ./scripts/build-docs.sh

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
