name: CMake

on: [push]

env:
  BUILD_TYPE: Release
  SRC_DIR: ${{github.workspace}}
  BUILD_DIR: $SRC_DIR/build
  COVERAGE_FILE: $BUILD_DIR/coverage/cov.info

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      shell: bash
      working-directory: $SRC_DIR
      run: $SRC_DIR/scripts/install-dependencies.sh

    - name: Build
      shell: bash
      working-directory: $SRC_DIR
      run: $SRC_DIR/scripts/build.sh $BUILD_DIR $BUILD_TYPE

    - name: Test
      shell: bash
      working-directory: $SRC_DIR
      run: $SRC_DIR/scripts/test.sh $BUILD_DIR $BUILD_TYPE

    - name: Coverage
      shell: bash
      working-directory: $SRC_DIR
      run: $SRC_DIR/scripts/coverage.sh $BUILD_DIR $COVERAGE_FILE

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{secrets.github_token}}
        path-to-lcov: $COVERAGE_FILE
