name: Main

on: [push]

env:
  BUILD_TYPE: Release
  COVERAGE_FILE: ${{github.workspace}}/build/coverage/cov.info

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'

    - name: Install Dependencies
      shell: bash
      run: ./ci/install-deps.sh

    - name: Prepare
      shell: bash
      run: ./ci/submodules.sh

    - name: Configure
      shell: bash
      run: cmake -S . -B ./build

    - name: Build Library
      shell: bash
      run: cmake --build ./build --config $BUILD_TYPE

    - name: Build Documentation
      shell: bash
      run: cmake --build ./build --target docs

    - name: Test
      shell: bash
      run: cmake --build ./build --target test

    - name: Coverage
      shell: bash
      run: ./ci/coverage.sh $COVERAGE_FILE

    - name: Prepare Site
      shell: bash
      run: ./ci/site.sh $BUILD_TYPE

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{secrets.github_token}}
        path-to-lcov: ${{env.COVERAGE_FILE}}

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: site
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
